export const countries = [
  { name: "Sierra Leone", code: "SL", dial: "+232" },
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Ghana", code: "GH", dial: "+233" },
  { name: "Kenya", code: "KE", dial: "+254" },
  { name: "South Africa", code: "ZA", dial: "+27" },
  { name: "United Kingdom", code: "GB", dial: "+44" },
  { name: "United States", code: "US", dial: "+1" },
  { name: "Canada", code: "CA", dial: "+1" },
  { name: "Australia", code: "AU", dial: "+61" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "Bangladesh", code: "BD", dial: "+880" },
  { name: "Egypt", code: "EG", dial: "+20" },
  { name: "Morocco", code: "MA", dial: "+212" },
  { name: "Tanzania", code: "TZ", dial: "+255" },
  { name: "Uganda", code: "UG", dial: "+256" },
  { name: "Cameroon", code: "CM", dial: "+237" },
  { name: "Ivory Coast", code: "CI", dial: "+225" },
  { name: "Senegal", code: "SN", dial: "+221" },
  { name: "Zimbabwe", code: "ZW", dial: "+263" },
  { name: "Zambia", code: "ZM", dial: "+260" },
  { name: "Ethiopia", code: "ET", dial: "+251" },
  { name: "Germany", code: "DE", dial: "+49" },
  { name: "France", code: "FR", dial: "+33" },
  { name: "Italy", code: "IT", dial: "+39" },
  { name: "Spain", code: "ES", dial: "+34" },
  { name: "Brazil", code: "BR", dial: "+55" },
  { name: "Mexico", code: "MX", dial: "+52" },
  { name: "Indonesia", code: "ID", dial: "+62" },
  { name: "Malaysia", code: "MY", dial: "+60" },
  { name: "Philippines", code: "PH", dial: "+63" },
  { name: "Thailand", code: "TH", dial: "+66" },
  { name: "Vietnam", code: "VN", dial: "+84" },
  { name: "Saudi Arabia", code: "SA", dial: "+966" },
  { name: "UAE", code: "AE", dial: "+971" },
  { name: "Qatar", code: "QA", dial: "+974" },
  { name: "Kuwait", code: "KW", dial: "+965" },
  { name: "Other", code: "XX", dial: "" },
];

export const packageTypes = [
  { id: "free", name: "Free Package", description: "Basic access to free tips" },
  { id: "vip", name: "VIP Package", description: "Premium tips with 80%+ accuracy" },
  { id: "special", name: "Special Package", description: "Exclusive high-stakes predictions" },
];
